<?php
declare(strict_types=1);

/**
 * Builds %APP_ROOT%/config.php from environment variables at container start.
 * Called by docker/entrypoint.sh before apache starts (only if config.php is
 * missing or IBS_REGENERATE_CONFIG=1 — the latter also validates that every
 * required variable is set).
 *
 * Mapping (defaults = backoffice/config.example.php values):
 *   DB_DSN                    → db.dsn            (mysql:host=db;dbname=ibs;charset=utf8mb4)
 *   DB_USER / DB_PASSWORD     → db.user / db.password
 *   APP_NAME                  → app.name
 *   APP_DEBUG                 → app.debug
 *   APP_SECURE_COOKIES        → app.secure_cookies
 *   APP_SESSION_IDLE_MINUTES  → app.session_idle_minutes
 *   APP_SESSION_MAX_HOURS     → app.session_max_hours
 *   LOGIN_MAX_FAILURES_PER_USER → login.max_failures_per_user
 *   LOGIN_MAX_FAILURES_PER_IP   → login.max_failures_per_ip
 *   LOGIN_WINDOW_MINUTES      → login.window_minutes
 */

$root = getenv('APP_ROOT') ?: '/var/www/html';

$bool = static function (string $name, bool $default): bool {
    $v = getenv($name);
    return $v === false ? $default : in_array(strtolower($v), ['1', 'true', 'yes', 'on'], true);
};
$int = static function (string $name, int $default): int {
    $v = getenv($name);
    return $v === false || $v === '' ? $default : (int) $v;
};
$str = static function (string $name, string $default): string {
    $v = getenv($name);
    return $v === false || $v === '' ? $default : $v;
};

$config = [
    'db' => [
        // Container-local service name of the compose DB service.
        'dsn' => $str('DB_DSN', sprintf(
            'mysql:host=%s;dbname=%s;charset=utf8mb4',
            $str('DB_HOSTNAME', 'db'),
            $str('DB_NAME', 'ibs')
        )),
        'user' => $str('DB_USER', ''),
        'password' => $str('DB_PASSWORD', ''),
    ],
    'app' => [
        'name' => $str('APP_NAME', 'Imperiales Sicherheitsbüro'),
        'debug' => $bool('APP_DEBUG', false),
        'secure_cookies' => $bool('APP_SECURE_COOKIES', true),
        'session_idle_minutes' => $int('APP_SESSION_IDLE_MINUTES', 30),
        'session_max_hours' => $int('APP_SESSION_MAX_HOURS', 8),
    ],
    'login' => [
        'max_failures_per_user' => $int('LOGIN_MAX_FAILURES_PER_USER', 5),
        'max_failures_per_ip' => $int('LOGIN_MAX_FAILURES_PER_IP', 20),
        'window_minutes' => $int('LOGIN_WINDOW_MINUTES', 15),
    ],
];

if ($config['db']['user'] === '' || $config['db']['password'] === '') {
    fwrite(STDERR, "make-config.php: DB_USER / DB_PASSWORD not set, refusing to write config\n");
    exit(1);
}

$path = $root . '/config.php';
$php = "<?php\n\ndeclare(strict_types=1);\n\n// Generated by docker/make-config.php from container env — do NOT edit by hand.\n\nreturn " . var_export($config, true) . ";\n";
file_put_contents($path, $php);
chmod($path, 0640);
chown($path, 'www-data');
chgrp($path, 'www-data');
echo "config.php written to {$path}\n";
